version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "8/geTo'7l0f4"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
        - ./sqlserver-data/volumes/sqlserver:/var/opt/mssql/data
  library-app:
    build: .
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "8/geTo'7l0f4"
      Database: "TodoListDb"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports: 
      - "8090:80"